image: alfio/alf.io

stages:
    - build
    #- test
    #- deploy

before_script:
    - echo `pwd` # debug
    - docker info
    - which javac
    #  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
    #- export GRADLE_USER_HOME=`pwd`/.gradle

#cache:
#    paths:
#        - .gradle/wrapper
#        - .gradle/caches
#
build:
    stage: build
    script:
        - ./gradlew -version
#        - ./gradlew assemble
#    artifacts:
#        paths:
#            - build/libs/*.jar
#        expire_in: 1 week
#    only:
#        - master
#
#test:
#    stage: test
#    script:
#        - ./gradlew check
#
#deploy:
#    stage: deploy
#    script:
#        - ./deploy
#
#after_script:
#    - echo "End CI"